kind: Service
apiVersion: v1
metadata:
  annotations:
  name: ssa-liberty
  namespace: liberty-service
  labels:
    app: ssa-liberty
    app.kubernetes.io/instance: ssa-liberty
    app.kubernetes.io/name: ssa-liberty
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9080
  selector:
    app.kubernetes.io/instance: ssa-liberty
    app.kubernetes.io/name: ssa-liberty
  type: ClusterIP
  sessionAffinity: None

